### ISSUE TITLE
Toggle behaviour of the data source restful_resource to silently fail if ID does not exist

### ISSUE THREAD

**Issue by LaurentLesle** [magodo/terraform-provider-restful#45]
This issue is a request to add a new feature to the data source restful_resource to adjust the behaviour when an ID does not exist. Today the provider return an error 404 if the ID does not exist.

The proposed solution is to add a new attribute to return a null output value instead of the error 404.

```
data "restful_resource" "test" {
  id = "/posts/1"
  throw_error_if_not_exists = false
}

data.restful_resource.test.output (null if id does not exist)
```

throw_error_if_not_exists (default to true)

**Comment by magodo** [comment]
This is the default behavior of terraform, I assume this flag violate the behavior that Terraform expects, which might bring more confusions?

**Comment by LaurentLesle** [comment]
There is already both behaviour in the Terraform projects. In the above issue I was proposing to leave the error exception by default and only opt-in to change the behaviour when needed.

See two examples with Azurerm provider: 

<img width="754" alt="image" src="https://user-images.githubusercontent.com/4702224/212834300-58c72e87-7053-4eb5-b2d1-7efbd819eb39.png">


and

<img width="522" alt="image" src="https://user-images.githubusercontent.com/4702224/212834573-3703f6b7-9c29-417e-9067-f70612ebfc16.png">

**Comment by magodo** [comment]
What do you expect the value of the `example` when the data source doesn't exist? I think it is invalid to reference it via expression like `data.azurerm_resource_group.example.id`?

**Comment by LaurentLesle** [comment]
Something like that

```
data "restful_resource" "test" {
  id = "/posts/1"
  throw_error_if_not_exists = false
}

data.restful_resource.test.id = "/posts/1"
data.restful_resource.test.output = null
```

I think id should be kept to the value it was set.

**Comment by magodo** [comment]
I've made a test on the data source `azurerm_resource_group`. By default it will fail if the specified resource group name doesn't exist. If I manually change the behavior of it to not error but silently return on absent. Then given following config:

```hcl
data "azurerm_resource_group" "test" {
  name = "nonexists"
}

output "id" {
  value = data.azurerm_resource_group.test.id
}

output "name" {
  value = data.azurerm_resource_group.test.name
}

#output "tags" {
#  value = data.azurerm_resource_group.test.tags["foo"]
#}
```

The `id` and `name` doesn't exist in the output variable, I assume that is because their values are null. While if I uncomment the `tags`, it will error as I'm referencing a key in a null map.

Back to your requirement, I can add an option to allow users to choose whether error or not on absent resource. But I might concern whether in that case, we shall still keep the input properties, as in that case you are literaly referencing a property from a non-existed resource, which might be weired to users that it returns a non-nil value.

**Comment by LaurentLesle** [comment]
This requirement is only to cover some conditional situations.
For example I can check status of a resource (may or may not exist) and if running or if the response is null then I can tigger an operation

```
data "restful_resource" "resource_exist" {
  id = "/resource/1"
  throw_error_if_not_exists = false
}

// If the previous command through an error, the following cannot be executed.
// using throw_error_if_not_exists = false
// will unblock that

resource "restful_operation" "trigger_an_operation" {
  count = data.restful_resource.resource_exist.output == null ? 1 : 0

  path = ...
  method = "POST"
 ....
}

```

**Comment by magodo** [comment]
@LaurentLesle If this is the case (only referencing the output, rather need to persist the input props), then I think it is a valid use case.
